name: Veracode SCA

on:
  push:
  workflow_dispatch:

jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: Scan remote repository for Issues

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: app:latest

      - name: Docker Images List
        run: docker images

      # Download the Veracode Static Analysis Pipeline scan jar
      - run: curl --silent --show-error --fail -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      - run: unzip -o pipeline-scan-LATEST.zip

      # Run Veracode Static Analysis Pipeline scan
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
      - run: java -jar pipeline-scan.jar --veracode_api_id "${{secrets.VID}}" --veracode_api_key "${{secrets.VKEY}}" --file ./

      # Convert pipeline scan output to SARIF format
      - name: Convert pipeline scan output to SARIF format
        id: convert
        uses: veracode/veracode-pipeline-scan-results-to-sarif@ff08ae5b45d5384cb4679932f184c013d34da9be
        with:
          pipeline-results-json: results.json

      # Upload SARIF file for code scanning alerts
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: veracode-results.sarif
