name: Veracode SCA

on: 
  push:
  workflow_dispatch:
    
    
jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: Scan remote repository for Issues

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: app:latest
      - name: docker ls
        run: |
          docker images 
      - name: Verracode Container/IaC/Secrets action step
        uses: veracode/container_iac_secrets_scanning@v1.0.0
        with:
          vid: ${{ secrets.VID }}
          vkey: ${{ secrets.VKEY }}
          command: "scan" 
          type: "directory"
          source: "./"
          format: "json"
          debug: false
          fail_build: false
# Convert pipeline scan output to SARIF format
      - name: Convert pipeline scan output to SARIF format
        id: convert
        uses: veracode/veracode-pipeline-scan-results-to-sarif@ff08ae5b45d5384cb4679932f184c013d34da9be
        with:
          pipeline-results-json: results.json

      # Upload SARIF file for code scanning alerts
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: veracode-results.sarif
