name: Veracode SCA

on:
  push:
  workflow_dispatch:
    
jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: Build and Scan Docker Image

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Add your build steps here to build the Docker image
      - name: Build Docker Image
        run: |
          # Replace the following command with your actual build commands
          docker build -t app:latest .

      # Download the Veracode Static Analysis Pipeline scan jar
      - run: curl --silent --show-error --fail -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
      - run: unzip -o pipeline-scan-LATEST.zip

      # Scan the Docker image using the Veracode Static Analysis Pipeline scan
      - uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
      - run: java -jar pipeline-scan.jar --veracode_api_id "${{secrets.VID}}" --veracode_api_key "${{secrets.VKEY}}" --file ./Dockerfile --verbose

      # Convert pipeline scan output to SARIF format
      - name: Convert pipeline scan output to SARIF format
        id: convert
        uses: veracode/veracode-pipeline-scan-results-to-sarif@ff08ae5b45d5384cb4679932f184c013d34da9be
        with:
          pipeline-results-json: results.json

      # Upload SARIF file for code scanning alerts
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: veracode-results.sarif
